name: Visual911
options:
  bundleIdPrefix: com.visual911
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

packages:
  SmartSpectra:
    url: https://github.com/Presage-Security/SmartSpectra
    from: "1.0.0"
  WebRTC:
    url: https://github.com/stasel/WebRTC
    from: "125.0.0"

targets:
  Visual911:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "project.yml"
          - "Info.plist"
          - "*.xcodeproj"
          - "*.xcworkspace"
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        NSCameraUsageDescription: "Visual911 needs camera access to measure your vitals and stream video to the dispatcher."
        NSMicrophoneUsageDescription: "Visual911 needs microphone access so the dispatcher can hear you during the emergency call."
        NSLocationWhenInUseUsageDescription: "Visual911 sends your location to the dispatcher so emergency services can find you."
        NSLocalNetworkUsageDescription: "Visual911 connects to the dispatch server on your local network."
        NSBonjourServices:
          - _http._tcp
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
          NSExceptionDomains:
            152.23.73.108:
              NSExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.visual911.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: SmartSpectra
        product: SmartSpectraSwiftSDK
      - package: WebRTC
