name: Visual911
options:
  bundleIdPrefix: com.visual911
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

packages:
  SmartSpectra:
    url: https://github.com/Presage-Security/SmartSpectra
    from: "1.0.0"
  WebRTC:
    url: https://github.com/stasel/WebRTC
    from: "125.0.0"

targets:
  Visual911:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "project.yml"
          - "Info.plist"
          - "*.xcodeproj"
          - "*.xcworkspace"
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.visual911.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: SmartSpectra
        product: SmartSpectraSwiftSDK
      - package: WebRTC
      - framework: AVFoundation.framework
        implicit: true
      - framework: CoreLocation.framework
        implicit: true
      - sdk: CryptoKit.framework
        implicit: true
